apiVersion: v1
kind: Service
metadata:
{{- if .Values.server.service.annotations }}
  annotations:
{{ toYaml .Values.server.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.server.service.labels }}
{{ toYaml .Values.server.service.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus.server.fullname" . }}
spec:
{{- if .Values.server.service.clusterIP }}
  clusterIP: {{ .Values.server.service.clusterIP }}
{{- end }}
{{- if .Values.server.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.server.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.server.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.server.service.loadBalancerIP }}
{{- end }}
{{- if .Values.server.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.server.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
{{- if eq .Values.server.service.type "NodePort" }}
{{- if .Values.thanosSidecar.enabled }}
  externalTrafficPolicy: Cluster
{{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.server.service.servicePort }}
      protocol: TCP
      targetPort: 9090
      {{- if eq .Values.server.service.type "NodePort" }}
      {{- if .Values.server.service.nodePort }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{- end }}
      {{- end }}
{{- if .Values.thanosSidecar.enabled }}
    - name: gossip
      port: 10900
      protocol: TCP
      targetPort: cluster
      {{- if eq .Values.server.service.type "NodePort" }}
      nodePort: 30900
      {{- end }}
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: http
      {{- if eq .Values.server.service.type "NodePort" }}
      nodePort: 30901
      {{- end }}
    - name: http-sidecar-metrics
      port: 10902
      protocol: TCP
      targetPort: http
      {{- if eq .Values.server.service.type "NodePort" }}
      nodePort: 30902
      {{- end }}
{{- end }}
  selector:
    app: {{ template "prometheus.name" . }}
    component: "{{ .Values.server.name }}"
    release: {{ .Release.Name }}
  type: "{{ .Values.server.service.type }}"
